---
title: "eds212_day2_activities"
author: "zachyloo"
format: html
editor: visual
---

## Section 3. Derivatives in R

Find the derivative expression & slope at indicated value for each function below:

$f(x) = x^2$ at x=3

```{r}
exp_1 <- expression(x^2)
deriv_1 <- D(expr = exp_1, name = "x")

# evaluate at x = 3
x <- 3
eval(deriv_1)
```

For this function, at x = 3, the slope is 6

$P(a) = 2(3a + 2)^4 - 5$

```{r}
exp_2 <- expression(2* (3 * a + 2 )^4 - 5)
deriv_2 <- D(expr = exp_2, name = "a")

# evaluate at a = 1.2
a <- 1.2
eval(deriv_2)
```

For this function, at a = 1.2, the slope is 4214.784

## Section 4. More Penguins Please

```{r}
library(tidyverse)
library(palmerpenguins)
#need to know column names
head(penguins)
```

```{r}
# create plot
ggplot(data = penguins, aes(x =  bill_length_mm, y = bill_depth_mm)) + 
  geom_point(aes(color = species)) + 
  scale_color_manual(values = c("yellow2", "orange","darkblue")) +
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       title = "Penguin's Bills by Species") +
  facet_wrap(~species) +
  theme_minimal()
```

```{r}
# new jitter plot
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + 
  geom_jitter(aes(color = species)) +
  scale_color_manual(values = c("pink", "lightgreen", "purple")) +
  labs(x = "Species",
       y = "Flipper Length (mm)",
       title = "Penguin Species Comparison of Flipper Length") + 
  theme_minimal()
```
